-- Generated by the Practicora V6 installer.
-- Run after supabase/schema.sql and after this account exists in Supabase Auth.
select public.bootstrap_practicora_platform_owner('jessicatchikapa@gmail.com');
