"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowRight, BookOpenCheck, BarChart3, FileText, LayoutDashboard, X } from "lucide-react";
import { translate as t } from "@/i18n";
import { Button } from "@/components/ui/button";
const KEY="practicora:onboarding-tour:v1";
export function OnboardingTour({locale}:{locale:string}){const[open,setOpen]=useState(false);const[step,setStep]=useState(0);useEffect(()=>{if(localStorage.getItem(KEY)!=="complete"){const timer=window.setTimeout(()=>setOpen(true),700);return()=>window.clearTimeout(timer)}},[]);if(!open)return null;const items=[{icon:LayoutDashboard,title:t(locale,"app.onboarding.workspace_title"),description:t(locale,"app.onboarding.workspace_description"),href:`/${locale}/app`},{icon:BookOpenCheck,title:t(locale,"app.onboarding.journal_title"),description:t(locale,"app.onboarding.journal_description"),href:`/${locale}/app/journal/new`},{icon:BarChart3,title:t(locale,"app.onboarding.analytics_title"),description:t(locale,"app.onboarding.analytics_description"),href:`/${locale}/app/analytics`},{icon:FileText,title:t(locale,"app.onboarding.reports_title"),description:t(locale,"app.onboarding.reports_description"),href:`/${locale}/app/reports`}];const item=items[step];const Icon=item.icon;function done(){localStorage.setItem(KEY,"complete");setOpen(false)}return <div className="fixed inset-0 z-[10040] flex items-end justify-center bg-[#06131c]/45 p-3 backdrop-blur-[2px] sm:items-center" role="dialog" aria-modal="true"><div className="w-full max-w-md rounded-2xl border border-border bg-surface p-5 shadow-[var(--shadow-float)] practicora-soft-enter"><div className="flex items-start justify-between gap-3"><span className="flex size-11 items-center justify-center rounded-2xl bg-primary-softer text-primary"><Icon className="size-5"/></span><button onClick={done} className="rounded-lg p-2 text-muted transition-colors hover:bg-surface-muted hover:text-foreground" aria-label={t(locale,"app.onboarding.close")}><X className="size-4"/></button></div><p className="mt-5 text-xs font-bold uppercase tracking-[.12em] text-primary">{t(locale,"app.onboarding.step",{current:step+1,total:items.length})}</p><h2 className="mt-2 text-xl font-extrabold">{item.title}</h2><p className="mt-2 text-sm leading-6 text-muted">{item.description}</p><div className="mt-5 flex gap-1.5">{items.map((_,i)=><span key={i} className={`h-1.5 flex-1 rounded-full ${i<=step?"bg-primary":"bg-surface-strong"}`}/>)}</div><div className="mt-5 flex items-center justify-between gap-3"><Button variant="ghost" onClick={done}>{t(locale,"app.onboarding.skip")}</Button>{step<items.length-1?<Button onClick={()=>setStep((v)=>v+1)}>{t(locale,"app.onboarding.next")}<ArrowRight className="size-4"/></Button>:<ButtonLink href={item.href} onClick={done} label={t(locale,"app.onboarding.start")}/>}</div></div></div>}
function ButtonLink({href,onClick,label}:{href:string;onClick:()=>void;label:string}){return <Link href={href} onClick={onClick} className="inline-flex h-10 items-center justify-center gap-2 rounded-xl bg-primary px-4 text-sm font-bold text-white transition-colors hover:bg-primary-strong">{label}<ArrowRight className="size-4"/></Link>}
