"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { ArrowRight, Clock3, Search } from "lucide-react";
import { normalizeLocale, translate as t } from "@/i18n";
import type { BlogPost } from "@/lib/blog";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/field";
import { Select } from "@/components/ui/select";
import { FilterPanel } from "@/components/ui/filter-panel";
import { Pagination } from "@/components/ui/pagination";

export function BlogExplorer({ locale, posts }: { locale: string; posts: BlogPost[] }) {
  const lang = normalizeLocale(locale);
  const [open, setOpen] = useState(false); const [query, setQuery] = useState(""); const [category, setCategory] = useState("all"); const [reading, setReading] = useState("all"); const [sort, setSort] = useState("newest"); const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState(6);
  const categories = useMemo(() => Array.from(new Set(posts.map((post) => post.category[lang]))), [lang, posts]);
  const filtered = useMemo(() => { const q=query.trim().toLowerCase(); const rows=posts.filter((post)=>{const read=reading==="short"?post.readingMinutes<=5:reading==="medium"?post.readingMinutes>5&&post.readingMinutes<=10:reading==="long"?post.readingMinutes>10:true;return (category==="all"||post.category[lang]===category)&&read&&(!q||`${post.title[lang]} ${post.description[lang]}`.toLowerCase().includes(q));}); return rows.sort((a,b)=>sort==="oldest"?a.publishedAt.localeCompare(b.publishedAt):sort==="reading"?a.readingMinutes-b.readingMinutes:b.publishedAt.localeCompare(a.publishedAt)); },[category,lang,posts,query,reading,sort]);
  const pageCount=Math.max(1,Math.ceil(filtered.length/pageSize)); const safePage=Math.min(page,pageCount); const visible=filtered.slice((safePage-1)*pageSize,safePage*pageSize);
  function clear(){setQuery("");setCategory("all");setReading("all");setSort("newest");setPage(1)}
  return <section className="mx-auto max-w-[1100px] px-4 py-14 sm:px-6 lg:px-8"><FilterPanel title={t(locale,"marketing.blog.filters")} summary={t(locale,"marketing.blog.result_count",{count:filtered.length})} open={open} onOpenChange={setOpen} onClear={clear} clearLabel={t(locale,"marketing.blog.clear_filters")}><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><div className="relative"><Search className="pointer-events-none absolute left-3.5 top-1/2 size-4 -translate-y-1/2 text-muted"/><Input className="pl-10" value={query} onChange={(e)=>{setQuery(e.target.value);setPage(1)}} placeholder={t(locale,"marketing.blog.search_placeholder")}/></div><Select value={category} onValueChange={(v)=>{setCategory(v);setPage(1)}} options={[{value:"all",label:t(locale,"marketing.blog.all_categories")},...categories.map((v)=>({value:v,label:v}))]}/><Select value={reading} onValueChange={(v)=>{setReading(v);setPage(1)}} options={[{value:"all",label:t(locale,"marketing.blog.all_reading_times")},{value:"short",label:t(locale,"marketing.blog.reading_short")},{value:"medium",label:t(locale,"marketing.blog.reading_medium")},{value:"long",label:t(locale,"marketing.blog.reading_long")}]}/><Select value={sort} onValueChange={setSort} options={[{value:"newest",label:t(locale,"marketing.blog.sort_newest")},{value:"oldest",label:t(locale,"marketing.blog.sort_oldest")},{value:"reading",label:t(locale,"marketing.blog.sort_reading")}]}/></div></FilterPanel><div className="mt-6"><Pagination locale={locale} page={safePage} pageSize={pageSize} total={filtered.length} onPageChange={setPage} onPageSizeChange={(v)=>{setPageSize(v);setPage(1)}} pageSizeOptions={[6,12,24]}/></div><div className="mt-5 grid gap-5 lg:grid-cols-2">{visible.map((post)=><Card key={post.slug} className="h-full transition-[transform,border-color,box-shadow] duration-200 hover:-translate-y-0.5 hover:border-primary/35 hover:shadow-md"><CardContent className="flex h-full flex-col"><div className="flex items-center justify-between gap-4 text-xs font-bold uppercase tracking-[.1em] text-primary"><span>{post.category[lang]}</span><span className="inline-flex items-center gap-1.5 text-muted"><Clock3 className="size-3.5"/>{post.readingMinutes} {t(locale,"common.misc.minutes_short")}</span></div><h2 className="mt-5 text-xl font-extrabold tracking-[-.025em]">{post.title[lang]}</h2><p className="mt-3 flex-1 text-sm leading-6 text-muted">{post.description[lang]}</p><Link className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-primary hover:text-primary-strong" href={`/${locale}/blog/${post.slug}`}>{t(locale,"marketing.blog.read_article")}<ArrowRight className="size-4"/></Link></CardContent></Card>)}</div></section>;
}
